// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: keyword.proto

package pbkeyword

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpdateAssociationTableServiceClient is the client API for UpdateAssociationTableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateAssociationTableServiceClient interface {
	UpdateAssociationTableFunc(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type updateAssociationTableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateAssociationTableServiceClient(cc grpc.ClientConnInterface) UpdateAssociationTableServiceClient {
	return &updateAssociationTableServiceClient{cc}
}

func (c *updateAssociationTableServiceClient) UpdateAssociationTableFunc(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/UpdateAssociationTableService/UpdateAssociationTableFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateAssociationTableServiceServer is the server API for UpdateAssociationTableService service.
// All implementations must embed UnimplementedUpdateAssociationTableServiceServer
// for forward compatibility
type UpdateAssociationTableServiceServer interface {
	UpdateAssociationTableFunc(context.Context, *EmptyMessage) (*EmptyMessage, error)
	mustEmbedUnimplementedUpdateAssociationTableServiceServer()
}

// UnimplementedUpdateAssociationTableServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUpdateAssociationTableServiceServer struct {
}

func (UnimplementedUpdateAssociationTableServiceServer) UpdateAssociationTableFunc(context.Context, *EmptyMessage) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssociationTableFunc not implemented")
}
func (UnimplementedUpdateAssociationTableServiceServer) mustEmbedUnimplementedUpdateAssociationTableServiceServer() {
}

// UnsafeUpdateAssociationTableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateAssociationTableServiceServer will
// result in compilation errors.
type UnsafeUpdateAssociationTableServiceServer interface {
	mustEmbedUnimplementedUpdateAssociationTableServiceServer()
}

func RegisterUpdateAssociationTableServiceServer(s grpc.ServiceRegistrar, srv UpdateAssociationTableServiceServer) {
	s.RegisterService(&UpdateAssociationTableService_ServiceDesc, srv)
}

func _UpdateAssociationTableService_UpdateAssociationTableFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateAssociationTableServiceServer).UpdateAssociationTableFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UpdateAssociationTableService/UpdateAssociationTableFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateAssociationTableServiceServer).UpdateAssociationTableFunc(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateAssociationTableService_ServiceDesc is the grpc.ServiceDesc for UpdateAssociationTableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateAssociationTableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UpdateAssociationTableService",
	HandlerType: (*UpdateAssociationTableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAssociationTableFunc",
			Handler:    _UpdateAssociationTableService_UpdateAssociationTableFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyword.proto",
}

// KeywordServiceClient is the client API for KeywordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeywordServiceClient interface {
	KeywordFunc(ctx context.Context, in *KeywordRequest, opts ...grpc.CallOption) (*KeywordResponse, error)
}

type keywordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeywordServiceClient(cc grpc.ClientConnInterface) KeywordServiceClient {
	return &keywordServiceClient{cc}
}

func (c *keywordServiceClient) KeywordFunc(ctx context.Context, in *KeywordRequest, opts ...grpc.CallOption) (*KeywordResponse, error) {
	out := new(KeywordResponse)
	err := c.cc.Invoke(ctx, "/KeywordService/KeywordFunc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeywordServiceServer is the server API for KeywordService service.
// All implementations must embed UnimplementedKeywordServiceServer
// for forward compatibility
type KeywordServiceServer interface {
	KeywordFunc(context.Context, *KeywordRequest) (*KeywordResponse, error)
	mustEmbedUnimplementedKeywordServiceServer()
}

// UnimplementedKeywordServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeywordServiceServer struct {
}

func (UnimplementedKeywordServiceServer) KeywordFunc(context.Context, *KeywordRequest) (*KeywordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeywordFunc not implemented")
}
func (UnimplementedKeywordServiceServer) mustEmbedUnimplementedKeywordServiceServer() {}

// UnsafeKeywordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeywordServiceServer will
// result in compilation errors.
type UnsafeKeywordServiceServer interface {
	mustEmbedUnimplementedKeywordServiceServer()
}

func RegisterKeywordServiceServer(s grpc.ServiceRegistrar, srv KeywordServiceServer) {
	s.RegisterService(&KeywordService_ServiceDesc, srv)
}

func _KeywordService_KeywordFunc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeywordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordServiceServer).KeywordFunc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KeywordService/KeywordFunc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordServiceServer).KeywordFunc(ctx, req.(*KeywordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeywordService_ServiceDesc is the grpc.ServiceDesc for KeywordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeywordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KeywordService",
	HandlerType: (*KeywordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KeywordFunc",
			Handler:    _KeywordService_KeywordFunc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "keyword.proto",
}
