// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: keyword.proto

package pbkeyword

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyword_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_keyword_proto_rawDescGZIP(), []int{0}
}

type ErrMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrString string `protobuf:"bytes,1,opt,name=errString,proto3" json:"errString,omitempty"`
}

func (x *ErrMessage) Reset() {
	*x = ErrMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyword_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrMessage) ProtoMessage() {}

func (x *ErrMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrMessage.ProtoReflect.Descriptor instead.
func (*ErrMessage) Descriptor() ([]byte, []int) {
	return file_keyword_proto_rawDescGZIP(), []int{1}
}

func (x *ErrMessage) GetErrString() string {
	if x != nil {
		return x.ErrString
	}
	return ""
}

type KeywordMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *KeywordMessage) Reset() {
	*x = KeywordMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyword_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeywordMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordMessage) ProtoMessage() {}

func (x *KeywordMessage) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordMessage.ProtoReflect.Descriptor instead.
func (*KeywordMessage) Descriptor() ([]byte, []int) {
	return file_keyword_proto_rawDescGZIP(), []int{2}
}

func (x *KeywordMessage) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type KeywordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords         []*KeywordMessage `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
	NumberOfKeywords int32             `protobuf:"varint,2,opt,name=numberOfKeywords,proto3" json:"numberOfKeywords,omitempty"`
}

func (x *KeywordRequest) Reset() {
	*x = KeywordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyword_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeywordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordRequest) ProtoMessage() {}

func (x *KeywordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordRequest.ProtoReflect.Descriptor instead.
func (*KeywordRequest) Descriptor() ([]byte, []int) {
	return file_keyword_proto_rawDescGZIP(), []int{3}
}

func (x *KeywordRequest) GetKeywords() []*KeywordMessage {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *KeywordRequest) GetNumberOfKeywords() int32 {
	if x != nil {
		return x.NumberOfKeywords
	}
	return 0
}

type KeywordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keywords []*KeywordMessage `protobuf:"bytes,1,rep,name=keywords,proto3" json:"keywords,omitempty"`
}

func (x *KeywordResponse) Reset() {
	*x = KeywordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keyword_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeywordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeywordResponse) ProtoMessage() {}

func (x *KeywordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keyword_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeywordResponse.ProtoReflect.Descriptor instead.
func (*KeywordResponse) Descriptor() ([]byte, []int) {
	return file_keyword_proto_rawDescGZIP(), []int{4}
}

func (x *KeywordResponse) GetKeywords() []*KeywordMessage {
	if x != nil {
		return x.Keywords
	}
	return nil
}

var File_keyword_proto protoreflect.FileDescriptor

var file_keyword_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x2a, 0x0a, 0x0a, 0x45, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x72, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x72, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x2a, 0x0a, 0x0e, 0x4b,
	0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x69, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x6b, 0x65, 0x79,
	0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x4f, 0x66, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x10, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x32, 0x5b, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x46, 0x75, 0x6e,
	0x63, 0x12, 0x0d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x0b, 0x2e, 0x45, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x32,
	0x44, 0x0a, 0x0e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x32, 0x0a, 0x0b, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x46, 0x75, 0x6e, 0x63,
	0x12, 0x0f, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x6b, 0x65,
	0x79, 0x77, 0x6f, 0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keyword_proto_rawDescOnce sync.Once
	file_keyword_proto_rawDescData = file_keyword_proto_rawDesc
)

func file_keyword_proto_rawDescGZIP() []byte {
	file_keyword_proto_rawDescOnce.Do(func() {
		file_keyword_proto_rawDescData = protoimpl.X.CompressGZIP(file_keyword_proto_rawDescData)
	})
	return file_keyword_proto_rawDescData
}

var file_keyword_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_keyword_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),    // 0: EmptyMessage
	(*ErrMessage)(nil),      // 1: ErrMessage
	(*KeywordMessage)(nil),  // 2: KeywordMessage
	(*KeywordRequest)(nil),  // 3: KeywordRequest
	(*KeywordResponse)(nil), // 4: KeywordResponse
}
var file_keyword_proto_depIdxs = []int32{
	2, // 0: KeywordRequest.keywords:type_name -> KeywordMessage
	2, // 1: KeywordResponse.keywords:type_name -> KeywordMessage
	0, // 2: UpdateAssociationTableService.UpdateAssociationTableFunc:input_type -> EmptyMessage
	3, // 3: KeywordService.KeywordFunc:input_type -> KeywordRequest
	1, // 4: UpdateAssociationTableService.UpdateAssociationTableFunc:output_type -> ErrMessage
	4, // 5: KeywordService.KeywordFunc:output_type -> KeywordResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_keyword_proto_init() }
func file_keyword_proto_init() {
	if File_keyword_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keyword_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keyword_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keyword_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeywordMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keyword_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeywordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_keyword_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeywordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keyword_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_keyword_proto_goTypes,
		DependencyIndexes: file_keyword_proto_depIdxs,
		MessageInfos:      file_keyword_proto_msgTypes,
	}.Build()
	File_keyword_proto = out.File
	file_keyword_proto_rawDesc = nil
	file_keyword_proto_goTypes = nil
	file_keyword_proto_depIdxs = nil
}
